name: app_restoran
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  url_launcher: ^6.0.20
  http: ^0.13.5
  provider: ^6.0.3
  flutter_layout_grid: ^2.0.1
  connectivity_plus: ^2.3.7
  intl: ^0.17.0
  android_alarm_manager_plus: ^2.0.8
  flutter_local_notifications: ^12.0.2
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.5

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo-dark.png
  color_dark: "#000000"
  image_dark: assets/logo-terang.png
  android: true
  ios: true

flutter:
  uses-material-design: true
